version: 0.0
os: linux
files:
  - source: 'C:\Users\sai prasad\Downloads\sai CICD\code'
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    mode: "0755"
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
ApplicationStart:
  - location: deploy-scripts/application-start-hook.sh
    timeout: 300
